numpy（Numerical Python）提供了python对多维数组对象的支持：ndarray
1.创建ndarray数组
ndarray：N维数组对象（矩阵），所有元素必须是相同类型。 
ndarray属性：ndim属性，表示维度个数；shape属性，表示各维度大小；dtype属性，表示数据类型。

In [27]:
import numpy

print ('使用列表生成一维数组')
data = [1,2,3,4,5,6]
x = numpy.array(data)
print (x) #打印数组
print ((x).dtype) #打印数组元素的类型


使用列表生成一维数组
[1 2 3 4 5 6]
int32


In [29]:
print ('使用列表生成二维数组')
data = [[1,2],[3,4],[5,6]]
x = numpy.array(data)
print (x) #打印数组
print ((x).ndim) #打印数组的维度
print ((x).shape) #打印数组各个维度的长度。shape是一个元组

使用列表生成二维数组
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


使用zero/ones/empty创建数组:根据shape来创建

In [30]:
x=numpy.zeros(6)
print (x)

[0. 0. 0. 0. 0. 0.]


In [31]:
x=numpy.zeros((2,3))
print (x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x=numpy.ones((2,3))
print (x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
x=numpy.empty((3,3))
print (x)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.50587869e-321]
 [1.14799972e-311 0.00000000e+000 3.23815565e-319]]


使用arrange生成连续元素

In [38]:
x=numpy.arange(6)
print (x)

[0 1 2 3 4 5]


In [39]:
x=numpy.arange(0,6,2)
print (x)

[0 2 4]


2.指定ndarray数组元素的类型

In [41]:
x=numpy.array([1,2.3,4],dtype=numpy.int64)
print (x)

[1 2 4]


In [42]:
x=numpy.array([1,2.3,4],dtype=numpy.float64)
print (x)

[1.  2.3 4. ]


使用astype复制数组，并转换类型

In [44]:
x=numpy.array([1,2.3,4],dtype=numpy.float64)
y=x.astype(numpy.int32)
print (y)

[1 2 4]


In [45]:
print (x)

[1.  2.3 4. ]


In [46]:
z = y.astype(numpy.float64)
print (z)

[1. 2. 4.]


将字符串元素转换为数值元素

In [49]:
x = numpy.array(['1','2','3'],dtype = numpy.string_)
y = x.astype(numpy.int32)
print (x)
print (y)

[b'1' b'2' b'3']
[1 2 3]


使用其他数组的数据类型作为参数

In [53]:
x = numpy.array([ 1., 2.6,3. ],dtype = numpy.float32)
y = numpy.arange(3,dtype=numpy.int32)
print (y)
print (y.astype(x.dtype))

[0 1 2]
[0. 1. 2.]


3.ndarray的矢量化计算

In [57]:
print ('ndarray数组与标量/数组的运算')
x=numpy.array([1,2,3])
print (x*2)
print (x>2)
y=numpy.array([4,5,6])
print (x+y)
print (x>y)

ndarray数组与标量/数组的运算
[2 4 6]
[False False  True]
[5 7 9]
[False False False]


4.ndarray数组的基本索引和切片

In [61]:
print ('ndarray的基本索引')
x = numpy.array([[1,2],[3,4],[5,6]])
print (x[0])
print (x[0][1])    #普通python数组的索引
print (x[0,1])     #ndarray数组的索引

ndarray的基本索引
[1 2]
2
2


In [62]:
x = numpy.array([[[1, 2], [3,4]], [[5, 6], [7,8]]])
print (x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
print (x[0])

[[1 2]
 [3 4]]


In [67]:
y=(x[0].copy())
z=x[0]
print (y)
print (y[0,0])

[[1 2]
 [3 4]]
1


In [69]:
y[0,0] = 0 
z[0,0] = -1
print (y)
print (x[0])
print (z) 

[[0 2]
 [3 4]]
[[-1  2]
 [ 3  4]]
[[-1  2]
 [ 3  4]]


ndarray的切片

In [70]:
x = numpy.array([1,2,3,4,5])
print (x[0:4:2])

[1 3]


In [72]:
x = numpy.array([[1,2],[3,4],[5,6]])
print (x[:2])

[[1 2]
 [3 4]]


In [73]:
print (x[:2,:1])

[[1]
 [3]]


In [74]:
x[:2,:1] = 0  # 用标量赋值
print (x)

[[0 2]
 [0 4]
 [5 6]]


In [75]:
x[:2,:1] = [[8],[6]]  # 用数组赋值
print (x)

[[8 2]
 [6 4]
 [5 6]]


5.ndarray数组的布尔索引和花式索引

In [76]:
print ('ndarray的布尔型索引')
x = numpy.array([3,2,3,1,3,0])
# 布尔型数组的长度必须跟被索引的轴长度一致
y = numpy.array([True,False,True,False,True,False]) 
print (x[y])

ndarray的布尔型索引
[3 3 3]


In [77]:
print (x[y==False])

[2 1 0]


In [78]:
print (x>=3)

[ True False  True False  True False]


In [79]:
print (x[~(x>=3)])

[2 1 0]


In [80]:
print ((x==2)|(x==1))

[False  True False  True False False]


In [81]:
print (x[(x==2)|(x==1)])

[2 1]


In [82]:
x[(x==2)|(x==1)] = 0
print (x)

[3 0 3 0 3 0]


花式索引：使用整型数组作为索引。

In [85]:
print ('ndarray的花式索引:使用整型数组作为索引')
x = numpy.array([1,2,3,4,5,6])
print (x[[0,1,2]]) 
print (x[[-1,-2,-3]]) 

ndarray的花式索引:使用整型数组作为索引
[1 2 3]
[6 5 4]
[[1 2]
 [3 4]]


In [87]:
x = numpy.array([[1,2],[3,4],[5,6]])
print (x[[0,1]])

[[1 2]
 [3 4]]


In [88]:
x = numpy.array([[1,2],[3,4],[5,6]])
print (x[[0,1],[0,1]])

[1 4]


In [89]:
x = numpy.array([[1,2],[3,4],[5,6]])
print (x[[0,1]][:,[0,1]])

[[1 2]
 [3 4]]


In [91]:
x = numpy.array([[1,2],[3,4],[5,6]])
# 使用numpy.ix_()函数增强可读性
print (x[numpy.ix_([0,1],[0,1])]) #同上 打印01行的01列 [[1,2],[3,4]]
x[[0,1],[0,1]] = [0,0]
print (x) # [[0,2],[3,0],[5,6]]

[[1 2]
 [3 4]]
[[0 2]
 [3 0]
 [5 6]]


6.ndarray数组的转置和轴对换

In [93]:
print ('ndarray数组的转置和轴对换')
k = numpy.arange(9) #[0,1,....8]
m = k.reshape((3,3)) # 改变数组的shape复制生成2维的，每个维度长度为3的数组
print (k) 
print (m) 
# 转置(矩阵)数组：T属性 : mT[x][y] = m[y][x]
print (m.T) 
# 计算矩阵的内积 xTx
print (numpy.dot(m,m.T)) # numpy.dot点乘

ndarray数组的转置和轴对换
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[  5  14  23]
 [ 14  50  86]
 [ 23  86 149]]


In [94]:
# 高维数组的轴对象
k = numpy.arange(8).reshape(2,2,2)
print (k) # [[[0 1],[2 3]],[[4 5],[6 7]]]
print (k[1][0][0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
4


In [95]:
# 轴变换 transpose 参数:由轴编号组成的元组
m = k.transpose((1,0,2)) # m[y][x][z] = k[x][y][z]
print (m) # [[[0 1],[4 5]],[[2 3],[6 7]]]
print (m[0][1][0])

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
4


In [96]:
# 轴交换 swapaxes (axes：轴)，参数:一对轴编号
m = k.swapaxes(0,1) # 将第一个轴和第二个轴交换 m[y][x][z] = k[x][y][z]
print (m) # [[[0 1],[4 5]],[[2 3],[6 7]]]
print (m[0][1][0])

[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]
4


In [98]:
# 使用轴交换进行数组矩阵转置
m = numpy.arange(9).reshape((3,3))
print (m) # [[0 1 2] [3 4 5] [6 7 8]]
print (m.swapaxes(1,0)) # [[0 3 6] [1 4 7] [2 5 8]]
print (m.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


7.ndarray通用函数

通用函数（ufunc）是一种对ndarray中的数据执行元素级运算的函数。

一元ufunc：

In [100]:
print ('一元ufunc示例')
x = numpy.arange(6)
print (x) # [0 1 2 3 4 5]
print (numpy.square(x)) # [ 0  1  4  9 16 25]
x = numpy.array([1.5,1.6,1.7,1.8])
y,z = numpy.modf(x)
print (y) # [ 0.5  0.6  0.7  0.8]
print (z) # [ 1.  1.  1.  1.]

一元ufunc示例
[0 1 2 3 4 5]
[ 0  1  4  9 16 25]
[0.5 0.6 0.7 0.8]
[1. 1. 1. 1.]


In [101]:
print ('二元ufunc代码示例')
x = numpy.array([[1,4],[6,7]])
y = numpy.array([[2,3],[5,8]])
print (numpy.maximum(x,y)) # [[2,4],[6,8]]
print (numpy.minimum(x,y)) # [[1,3],[5,7]]

二元ufunc代码示例
[[2 4]
 [6 8]]
[[1 3]
 [5 7]]


8.NumPy的where函数使用