1.对基本索引的理解

In [4]:
import numpy as np
data1 = np.arange(24).reshape(4, 6)
print (data1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [2]:
data1[3]

array([18, 19, 20, 21, 22, 23])

In [3]:
data1[2, 1]

13

2.对切片的理解

In [4]:
import numpy as np
data1 = np.arange(24).reshape(4, 6)
print (data1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [5]:
data1[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:
data1[:2][1]   # 结果，此时是切片后，在取出的数组上进行索引操作

array([ 6,  7,  8,  9, 10, 11])

In [8]:
data1[:2,1]    #对于二维数组是按照行列进行切块，已经不是单个切片 多个切片

array([1, 7])

In [9]:
data1[1, :2]    #这里是先进行了索引操作，再进行切片操作  等价于data1[1][:2]

array([6, 7])

In [10]:
data1[:2, 2:5]   #此处先进行行（0轴索引，即0行索引和1行索引被切出）切片，对切出来的结果再按列（1轴索引，即2列索引到4列索引被切出）切片

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [11]:
data1[:2, 2:5][0]   ## 切出来的数组依旧可以进行索引和切片操作，需要另起括号

array([2, 3, 4])

In [13]:
data1[:2, 2:5][0:2]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [14]:
data2 = np.arange(24).reshape(2, 3, 4)

In [15]:
print (data2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
data2[0][1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [17]:
data2[:, 1:3, 1:3]   # 这里是在0轴上的索引全部切出，一共只有两个索引，即数组的高维度的两大块内容，然后按1轴，也就是二维中的行索引切片，最后按照列切片

array([[[ 5,  6],
        [ 9, 10]],

       [[17, 18],
        [21, 22]]])

总结：当以逗号区别多个切片时，如果中括号内第一个值是切片，此时这个就是切片操作，无论逗号后边是切片([:1, :3])形式还是索引形式([:1, 3])。
    如果中括号内第一个值是索引，那么此时的操作就按索引来对待，逗号后边的是对索引取出的数组进行切片操作，也就是[2, :1]==[2][:1]

In [1]:
import numpy as np
data1 = np.arange(24).reshape(4, 6)
print (data1)
data1[:1,:3]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[0, 1, 2]])

In [2]:
data1[:1,3]

array([3])

In [3]:
data1[2,:1]

array([12])

In [4]:
data1[2][:1]

array([12])

3.花式索引

In [6]:
import numpy as np
arr = np.arange(32).reshape((8, 4))
print (arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [7]:
arr[[1, 3, 4, 5]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr[[1,3,4,6],[1,3,0,2]]  #等同于(1,1)(3,3)(4,0)(6,2)位置处的数值

array([ 5, 15, 16, 26])

In [9]:
arr[[1,3,4,6]][:, 1:3]    #取出不连续的行列块子集 先通过花式索引取出对应的非连续的数组，之后再结果之上进行行列取子集

array([[ 5,  6],
       [13, 14],
       [17, 18],
       [25, 26]])

In [10]:
arr[[1,3,4,6]][:, [1, 3]]   # 取非连续行，非连续列的数据   先取第1,3,4,6行 再取第1,3列

array([[ 5,  7],
       [13, 15],
       [17, 19],
       [25, 27]])